FROM golang:1.24-alpine

WORKDIR /app

# Install git and curl for air installation
RUN apk add --no-cache git curl

# Install Air (hot reload tool)
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /usr/local/bin

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
